flowchart LR
    User([User])
    
    User --- Role(Select Role)
    User --- Start(Start Interview)
    User --- Ans(Answer Question)
    User --- Sub(Submit Answer)
    User --- Rec(Receive Feedback)
    User --- ViewF(View Results)
    User --- Ret(Retry Interview)
